plugins {
    id 'application'
}

group 'net.sentientturtle'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = 1.24
    targetCompatibility = 1.24
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jspecify:jspecify:1.0.0")
    // Used by Sqlite SDE & SharedCache .static
    implementation 'com.almworks.sqlite4java:sqlite4java:1.0.392'
    // Used by JSONL SDE & search index
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.0'
}